---
server.port: 9292
server.servlet.context-path: /api

# Hibernate & JPA settings
# automatically add or update table
spring.jpa.hibernate.ddl-auto: update

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

#H2DB
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
