---
#server.port: 9292
server.servlet.context-path: /api

# Hibernate & JPA settings
# automatically add or update table
spring.jpa.hibernate.ddl-auto: update

#MySql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/OnlineShopping?serverTimezone=UTC
    username: root
    password: password
