---
#server.port: 9393
server.servlet.context-path: /api

#allow bean override for proxy
spring.main.allow-bean-definition-overriding: true

feign.hystrix.enabled: true

# Hibernate & JPA settings
# automatically add or update table
spring.jpa.hibernate.ddl-auto: update

#MySql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/OnlineShopping?serverTimezone=UTC
    username: root
    password: password

